-- Superseded migration retained for history compatibility.
-- The canonical Titanium booking schema lives in:
-- supabase/migrations/20260922_booking_system.sql
--
-- This file intentionally contains no SQL. Do not restore the previous
-- duplicate bookings schema from this migration.
